#https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: Stress, Ubuntu build v2

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [main]
    paths:
      - docker/stress.ubuntu/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  #*.ub = Build node is Ubuntu
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/stress.ubuntu.x86
  DOCKERFILE: docker/stress.ubuntu/stress.ubuntu.dockerfile
  DOCKERHUB_REPO: carlosrodlop/stress.ubuntu.x86

jobs:
  docker:
    uses: carlosrodlop/docker-lib/.github/workflows/_ci_container.shared.yaml@main
    with:
      image_name: ${{ github.repository }}/stress.ubuntu.x86
      dockerfile: docker/stress.ubuntu/stress.ubuntu.dockerfile
      dockerhub_repo: carlosrodlop/stress.ubuntu.x86
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
