name: Publish Terraform Image Package

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]
    paths:
      - .docker/ubuntu.tf/**
  # If the Publish K8s Image Package is updated
  workflow_run:
    workflows: ["Publish K8s Image Package"]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NAME: ubuntu.tf
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}.ubuntu.tf

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: docker/setup-buildx-action@v1
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/${{ env.NAME }}/${{ env.NAME }}.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #https://depot.dev/blog/docker-layer-caching-in-github-actions
          cache-from: type=gha
          cache-to: type=gha,mode=max
